### ISSUE TITLE
Bad Platform artifacts show up in build

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1976]
in the builds with Java 8

https://github.com/itemis/xtext-reference-projects/runs/2835856963?check_suite_focus=true
https://github.com/itemis/xtext-reference-projects/runs/2835856620?check_suite_focus=true

new plaform artifacts seem to be pulled
this leads to build failing

```
 * What went wrong:
Execution failed for task ':org.xtext.example.mydsl:generateXtext'.
> com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.UnsupportedClassVersionError: org/eclipse/core/runtime/OperationCanceledException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

```
2021-06-16T04:48:23.8460022Z 1    ERROR Mwe2Launcher       - org/eclipse/core/runtime/OperationCanceledException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
2021-06-16T04:48:23.8465375Z java.lang.UnsupportedClassVersionError: org/eclipse/core/runtime/OperationCanceledException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
2021-06-16T04:48:23.8469044Z 	at java.lang.ClassLoader.defineClass1(Native Method)
2021-06-16T04:48:23.8471712Z 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
2021-06-16T04:48:23.8474734Z 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
2021-06-16T04:48:23.8477789Z 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
2021-06-16T04:48:23.8480558Z 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
2021-06-16T04:48:23.8483125Z 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
2021-06-16T04:48:23.8486274Z 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
2021-06-16T04:48:23.8489455Z 	at java.security.AccessController.doPrivileged(Native Method)
2021-06-16T04:48:23.8492711Z 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
2021-06-16T04:48:23.8495707Z 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
2021-06-16T04:48:23.8508810Z 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
2021-06-16T04:48:23.8513500Z 	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.run(Mwe2Launcher.java:74)
2021-06-16T04:48:23.8518115Z 	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main(Mwe2Launcher.java:37)
2021-06-16T04:48:23.8523737Z 	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
2021-06-16T04:48:23.8527488Z 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by cdietrich** [comment]
![Bildschirmfoto 2021-06-16 um 07 46 57](https://user-images.githubusercontent.com/238736/122164472-2610d700-ce77-11eb-84dd-eb6a26089fbb.png)

**Comment by cdietrich** [comment]
emf ranges of death lead to new stuff pulled
i simply dont understand the bom crap.

**Comment by LorenzoBettini** [comment]
Are the Xtext POM/BOM using version ranges or is it someone else? I always see lots of EMF and Eclipse POMs inspected when running the exec-maven-plugin

**Comment by cdietrich** [comment]
no the ranges are in emf. and the bom does not seem to be used for platform dependencies.
and the optional gradle dependencies dont go into the pom

**Comment by cdietrich** [comment]
workaround for maven

```
					<dependency>
						<groupId>org.eclipse.xtext</groupId>
						<artifactId>org.eclipse.xtext.xtext.generator</artifactId>
						<version>${xtextVersion}</version>
							<exclusions>
								<exclusion>
									<groupId>org.eclipse.platform</groupId>
									<artifactId>org.eclipse.equinox.common</artifactId>
								</exclusion>
								<exclusion>
									<groupId>org.eclipse.platform</groupId>
									<artifactId>org.eclipse.core.runtime</artifactId>
								</exclusion>
							</exclusions>
					</dependency>
```

**Comment by LorenzoBettini** [comment]
the BOM is not used when running a Maven plugin: the BOM is used only when declaring project dependencies. If I understand correctly the problem shows up when running `exec-maven-plugin` right?

**Comment by cdietrich** [comment]
@LorenzoBettini yes its with the exec maven plugin

**Comment by LorenzoBettini** [comment]
Which is always a source of troubles :'(
As I said, when you specify dependencies in any Maven plugin configuration/execution the BOM and other dependency management stuff are not used...

**Comment by cdietrich** [comment]
this also seems to break all our builds
https://ci.eclipse.org/xtext/job/xtext-lib/job/master/46/console

**Comment by dhuebner** [comment]
Could we just run the build with Java11?

**Comment by cdietrich** [comment]
yes this is also a valid workaround (unfortunately this might lead to accidential use of java 11 api)

**Comment by oehme** [comment]
Coming here from the other issue @cdietrich created: I'm afraid I'm missing some context. Did Xtext upgrade its EMF version? Or does EMF have open version ranges that just pull in the latest stuff?

**Comment by cdietrich** [comment]
@oehme no Xtext uses emf, emf has ranges for core.runtime and equinox.common
Xtext also has deps to core.runtime and equinox.common but some of them are optional and are not in pom
so instead of the plaform version Xtext likes to have the newest are pulled

**Comment by oehme** [comment]
I just saw you have a BOM for this, which you already use here:

https://github.com/eclipse/xtext-core/blob/0a6606ee5091c48a716f74932bb6dd693cbee227/org.eclipse.xtext.tests/testdata/wizard-expectations/gradle/gradle.parent/build.gradle#L18

You can add this BOM to the `xtextTooling` configuration as well, then it will be used when resolving the dependencies of the incremental builder.

**Comment by cdietrich** [comment]
this workaround seems to help as well

```
	configurations.all {
	    resolutionStrategy { 
	        eachDependency { DependencyResolveDetails details ->
	            if (details.requested.group == 'org.eclipse.platform' && details.requested.name == 'org.eclipse.core.runtime') {
	                details.useVersion "3.19.0"
	            }
	            if (details.requested.group == 'org.eclipse.platform' && details.requested.name == 'org.eclipse.equinox.common') {
	                details.useVersion("3.13.0")
	            }
	        }
	    }
	}
```

**Comment by cdietrich** [comment]
> You can add this BOM to the xtextTooling configuration (after the line that applies the Xtend plugin), then it will be used when resolving the dependencies of the incremental builder.

@oehme any hint on how to do that

**Comment by oehme** [comment]
```
dependencies {
    compile platform("org.eclipse.xtext:xtext-dev-bom:$project.version")	
}
if (findProperty('compileXtend') == 'true') {
    apply plugin: 'org.xtext.xtend'
    xtextTooling platform("org.eclipse.xtext:xtext-dev-bom:$project.version")	
}
```

**Comment by cdietrich** [comment]
tried this but it does not seems to work
```
> Could not find method xtextTooling() for arguments [DefaultExternalModuleDependency{group='org.eclipse.xtext', name='xtext-dev-bom', version='2.26.0-SNAPSHOT', configuration='default'}] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
same with xtendTooling
> Could not find method xtendTooling() for arguments [DefaultExternalModuleDependency{group='org.eclipse.xtext', name='xtext-dev-bom', version='2.26.0-SNAPSHOT', configuration='default'}] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

**Comment by oehme** [comment]
Ah right, that's because there's one for each sourceSet. In that case we need loop:


```
configurations.all {
    if (name.endsWith("Tooling")) {
        dependencies {
            add(name, platform("org.eclipse.xtext:xtext-dev-bom:$project.version"))
        }
    }
}
```

**Comment by cdietrich** [comment]
unfortunately this still does not work. it now fails to find the XtendStandaloneSetup class
also the configurations seems to be *ToolingTest and *ToolingMain

**Comment by cdietrich** [comment]
the transitive hell is also in platform artifacts

**Comment by cdietrich** [comment]
it seems to work to manage this will exclusions manually, but how to find all places and exclustions
https://github.com/eclipse/xtext-core/compare/cd_xtext_issue1976
https://github.com/eclipse/xtext-xtend/compare/cd_xtext_issue1976

**Comment by oehme** [comment]
> unfortunately this still does not work. it now fails to find the XtendStandaloneSetup class

Ah damn it, that's because I used `defaultDependencies` in the Xtend plugin (which I shouldn't have done).  So please adjust the workaround to:

```
configurations.all {
    if (name.endsWith("Tooling")) {
        dependencies {
            add(name, "org.eclipse.xtend:org.eclipse.xtend.core:$project.version"))
            add(name, platform("org.eclipse.xtext:xtext-dev-bom:$project.version"))
        }
    }
}
```

**Comment by oehme** [comment]
> it seems to work to manage this will exclusions manually, but how to find all places and exclustions

You shouldn't need any exclusions - The fix above (applying the Xtext BOM) is the way to go. I can make applying that BOM easier in a future version, but for now the code above should do.

**Comment by cdietrich** [comment]
yes, but it does not seem to work yet.
https://ci.eclipse.org/xtext/job/xtext-lib/job/cd_xtext_issue1976b/2/console
https://github.com/eclipse/xtext-lib/compare/cd_xtext_issue1976b
the solution also needs to work with pure maven

**Comment by oehme** [comment]
Can you enable build scans, so I can easily see the dependencies that were resolved during those CI builds?

> the solution also needs to work with pure maven

So do I understand correctly: Xtext depends on a newer version of EMF. EMF pulls in a platform version that no longer runs on Java 8. But Xtext still wants to run on Java 8. In that case I'd say the EMF upgrade needs to be reverted. Please correct me if I understood the situation wrong.

**Comment by cdietrich** [comment]
no, xtext still depends on the same emf.

but emf (and also jdt have other platform dependencies in the style `[3.12.0,4.0.0)`
xtext bom pins them to a wanted/tested version e.g  `3.13.0`
now platform and jdt publish new maven artifacts e.g. `3.15.0`
which is now resolved instead of the wanted `3.13.0`

**Comment by cdietrich** [comment]
build scan can be found here https://scans.gradle.com/s/auzttsmqbodtm

**Comment by oehme** [comment]
> build scan can be found here https://scans.gradle.com/s/auzttsmqbodtm

Thanks, I can now see that we're not using the `xxxTooling` configurations at all, but we set a custom Xtend classpath. I had forgotten about this. It's in [this](https://github.com/eclipse/xtext-lib/blob/master/gradle/bootstrap-setup.gradle#L31) build script. So you need to add the BOM there.

**Comment by cdietrich** [comment]
still does not seem to work, but now gradle scans is down
https://ci.eclipse.org/xtext/job/xtext-lib/job/cd_xtext_issue1976b/4/console

**Comment by oehme** [comment]
Okay, I'll check out the project and get back to you.

**Comment by cdietrich** [comment]
@oehme  i am just stupid. deleted the platform method accidentially, put chaning seems not be enhough

**Comment by oehme** [comment]
I had a look and the problem is that the xtext-dev-bom does not mark these as "strict" versions and thus Gradle merely treats them as minimum requirements. I.e. [this line](https://github.com/eclipse/xtext-lib/blob/master/org.eclipse.xtext.dev-bom/build.gradle#L64) should probably be:

```
api("org.eclipse.platform:org.eclipse.equinox.common") { version { strictly("3.13.0") } }
 
```
This applies to any version where you can't deal with upgrades. The Gradle user guide has a [nice summary](https://docs.gradle.org/current/userguide/rich_versions.html) of all the ways you can express your version constraints, so you can see which applies best to each situation.

**Comment by cdietrich** [comment]
@oehme i assume we then need to do this for all lines?!?

i also dont see where this information is preserved in maven
as we do have the code split on 8 repos where 6 or so build with gradle
the dev bom is consumed from upstream just as maven artifact

```
      <dependency>
        <groupId>org.eclipse.platform</groupId>
        <artifactId>org.eclipse.equinox.common</artifactId>
        <version>3.13.0</version>
        <scope>compile</scope>
      </dependency>
```

**Comment by oehme** [comment]
Correcting myself: The BOM is already enough, the problem was that Gradle wasn't using it, because BOM support is specific to the java plugin and the root project did not have that plugin, so it just ignored the contents of the BOM. See https://github.com/eclipse/xtext-lib/pull/386 for the solution.

**Comment by cdietrich** [comment]
cool. now i need to figure out if the same can somehow be applied to 
https://github.com/itemis/xtext-reference-projects/tree/master/greetings-gradle/2.26.0

**Comment by oehme** [comment]
Now for the xtext-gradle-plugin, I'm planning a new release anyway. For that I'll add the BOM automatically, so normal Xtext users won't need any additional code. If you want to fix the reference projects in the meantime, you can do the workaround I had described earlier:

```
configurations.all {
    if (name.contains("Tooling")) {
        dependencies {
            add(name, "org.eclipse.xtend:org.eclipse.xtend.core:$xtextVersion"))
            add(name, platform("org.eclipse.xtext:xtext-dev-bom:$xtextVersion"))
        }
    }
}
``` 

The Maven plugin should import the BOM in [its own POM](https://github.com/eclipse/xtext-maven/blob/master/org.eclipse.xtext.maven.plugin/pom.xml#L14).

**Comment by cdietrich** [comment]
hmmm the xtext-maven plugin and the xtend-maven-plugin already make use of the bom (via their parents) 
https://github.com/eclipse/xtext-maven/blob/a771b4b8b9589d07391931f362332b2710697a1b/org.eclipse.xtext.maven.parent/pom.xml#L27
https://github.com/eclipse/xtext-xtend/blob/ae80a5c1bb09a61596cb9848331694d8ebc562ab/releng/org.eclipse.xtend.maven.parent/pom.xml#L33

thus the problem should affect the `maven-exec-plugin` sections only

**Comment by oehme** [comment]
Ah I didn't know it was only about the exec plugin. That's odd though, since it [uses the classpath of your project](https://github.com/mojohaus/exec-maven-plugin/blob/4a03cf44706fcb18b037bf6467c0777d8e40e892/src/main/java/org/codehaus/mojo/exec/AbstractExecMojo.java#L160), which is [managed by the BOM](https://github.com/itemis/xtext-reference-projects/blob/master/greetings-maven/2.26.0/org.xtext.example.mydsl.parent/pom.xml#L19).

**Comment by cdietrich** [comment]
we have an explicit dependency list for it https://github.com/itemis/xtext-reference-projects/blob/f0f5fdd938dc352a0a5d42a1d6eece5e63377890/greetings-tycho/2.26.0/org.xtext.example.mydsl/pom.xml#L40

**Comment by LorenzoBettini** [comment]
Yes, that's what I said in https://github.com/eclipse/xtext/issues/1976#issuecomment-862096854 I was wondering if we can get rid of `<includePluginDependencies>true</includePluginDependencies>` so that we could simply specify `org.eclipse.emf.mwe2.launch` as a dependency of the exec plugin configuration and take the other deps from the POM of the project? Who was the first to introduce the exec plugin configuration?

**Comment by oehme** [comment]
Isn't mwe2.launch the one that pulls in the problematic deps?

**Comment by LorenzoBettini** [comment]
By looking at https://github.com/eclipse/xtext/issues/1976#issuecomment-862095532 I thought it was `xtext.generator`

**Comment by cdietrich** [comment]
the problem is not the launch, it is the maven exec.
the launch config uses the target platform, so if you use newer eclipse you will have to use java 11 anyway. so this is no issue

**Comment by ewillink** [comment]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=574259

The change to BREE 11 for org.eclipse.core makes anything non-trivial using Java 8 a thing of the past.

**Comment by LorenzoBettini** [comment]
But I seem to understand the problem is different here: you want to build with Java 8 with an older version of Eclipse. With the BOM you have full control on dependencies for the project's dependencies but not for the exec plugin configuration dependencies (you have to manually set exclusions for unwanted dependencies in the exec plugin configuration, that's why I was wondering whether we can have the exec plugin configuration to reuse the project's dependencies, https://www.mojohaus.org/exec-maven-plugin/java-mojo.html#includePluginDependencies)

**Comment by cdietrich** [comment]
@LorenzoBettini i have the feeling we were doing this in the past, but also changed that.
https://github.com/itemis/xtext-reference-projects/blob/bd7ff370f35e8aeee191e1c68834b05451f30538/greetings-maven/2.13.0/org.xtext.example.mydsl/pom.xml#L18

i have not looked up why

**Comment by LorenzoBettini** [comment]
By the way, this problem only shows up with Gradle right?
I cannot reproduce that with Maven locally: I created a new Xtext project with Maven support (using Xtext 2.25) and Java 8, then changed the Xtext version in the parent POM with 2.26.0-SNAPSHOT and enabled Sonatype snapshot repository. The build runs fine with Java 8 (also the exec plugin).

**Comment by cdietrich** [comment]
@LorenzoBettini in maven it happens with tycho projects only

**Comment by LorenzoBettini** [comment]
Sorry, I meant I was using a Maven/Tycho project, and cannot reproduce that...

**Comment by cdietrich** [comment]
can you test with https://github.com/itemis/xtext-reference-projects/tree/master/greetings-tycho/2.26.0

**Comment by LorenzoBettini** [comment]
Yes, doing it right now... (by the way, you confirm that these are not Eclipse plugin projects right? I mean they're not meant to be imported in Eclipse)

**Comment by LorenzoBettini** [comment]
@cdietrich OK, I can reproduce the problem with https://github.com/itemis/xtext-reference-projects/tree/master/greetings-tycho/2.26.0 and I made an experiment concerning my proposal on NOT relying on dependencies in the plugin exec configuration and it works! I'll show in you a PR in a minute (but can you please confirm that that example is not meant to be imported in Eclipse?)

**Comment by cdietrich** [comment]
it is meant to. its basically the project that is created by the wiazrd.
there is also an integ test (swtbot) in that project that executes the wizard (with java 11 only though)
the problem is: why did we change it if it was this way before

**Comment by LorenzoBettini** [comment]
The alternative solution of not touching the MANIFEST but moving the dependencies from the exec plugin configuration to the project's dependencies works as well (since in that case the BOM is used)...

**Comment by cdietrich** [comment]
i propose we do the change for java11+ when tycho 2.4 is released and use the manifest for < java 11

**Comment by LorenzoBettini** [comment]
If I understand correctly with Tycho 2.4 the manifest would work as it is thanks to the additional bundles (but removing deps from the exec plugin would still be good). But Tycho 2 requires java 11 anyway, so for java 8 we would need to add the required bundles in the manifest and still remove the deps from exec plugin. Is that what you propose?

**Comment by ewillink** [comment]
It is indeed mandatory to use Java >= 11 for the VM that runs Tycho/Maven, but the resultant build, for me, respects the MANIFEST.MF BREE and so happily produces Java 5 and Java 8 Jars supporting onging usage of traditional versions.

**Comment by cdietrich** [comment]
i guess we could go with your workaround for java 8 and the tycho 2.4 way once it is out.

**Comment by cdietrich** [comment]
wold xtend-maven-plugin workarounds might also need modification e.g. for Xtext/Xtend 2.13

```
				<plugin>
					<groupId>org.eclipse.xtend</groupId>
					<artifactId>xtend-maven-plugin</artifactId>
					<version>${xtextVersion}</version>
					<executions>
						<execution>
							<goals>
								<goal>compile</goal>
								<goal>xtend-install-debug-info</goal>
								<goal>testCompile</goal>
								<goal>xtend-test-install-debug-info</goal>
							</goals>
						</execution>
					</executions>
					<configuration>
						<outputDirectory>${basedir}/src/main/xtend-gen</outputDirectory>
						<testOutputDirectory>${basedir}/src/test/xtend-gen</testOutputDirectory>
					</configuration>
					<dependencies>
						<dependency>
							<groupId>org.eclipse.jdt</groupId>
							<artifactId>org.eclipse.jdt.core</artifactId>
							<version>3.12.2</version>
							<exclusions>
				<exclusion>
					<groupId>org.eclipse.platform</groupId>
					<artifactId>org.eclipse.equinox.common</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.eclipse.platform</groupId>
					<artifactId>org.eclipse.core.runtime</artifactId>
				</exclusion>
			</exclusions>
						</dependency>
						<dependency>
							<groupId>org.eclipse.jdt</groupId>
							<artifactId>org.eclipse.jdt.compiler.apt</artifactId>
							<version>1.2.100</version>
							<exclusions>
				<exclusion>
					<groupId>org.eclipse.platform</groupId>
					<artifactId>org.eclipse.equinox.common</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.eclipse.platform</groupId>
					<artifactId>org.eclipse.core.runtime</artifactId>
				</exclusion>
			</exclusions>
						</dependency>
						<dependency>
							<groupId>org.eclipse.jdt</groupId>
							<artifactId>org.eclipse.jdt.compiler.tool</artifactId>
							<version>1.2.51</version>
							<exclusions>
				<exclusion>
					<groupId>org.eclipse.platform</groupId>
					<artifactId>org.eclipse.equinox.common</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.eclipse.platform</groupId>
					<artifactId>org.eclipse.core.runtime</artifactId>
				</exclusion>
			</exclusions>
```

**Comment by LorenzoBettini** [comment]
By the way, the problem running MWE2 can also be reproduced when run from Eclipse 2021-06

```
0    [main] ERROR mf.mwe2.launch.runtime.Mwe2Launcher  - org/eclipse/core/runtime/OperationCanceledException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
java.lang.UnsupportedClassVersionError: org/eclipse/core/runtime/OperationCanceledException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.run(Mwe2Launcher.java:74)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main(Mwe2Launcher.java:37)
```

The launch configuration must specify JavaSE-11 to avoid that:

```xml
<stringAttribute key="org.eclipse.jdt.launching.JRE_CONTAINER" value="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-11"/>
```

(It happens on a DSL where the project is configured for Java 8)

**Comment by cdietrich** [comment]
@LorenzoBettini i assume you created the project without maven and thus no tycho tp is created and also not selected correct? if you have a target file it should use old eclipse that still supports java 8

**Comment by LorenzoBettini** [comment]
Sorry I wasn't clear: in this project bundles require Java 8, but I have an Oomph setup that requires Java 11 (otherwise I wouldn't be able to use new Eclipse); the setup also runs the MWE2 launches, and when using 2021-06 as the target platform the launches fail because by default they use the same Java version of the bundles (Java 8). Since my workspace is setup with both JDK 8 and JDK 11, it actually runs the MWE2 workflow with JDK 8 in that case.

Thus, summarizing, if the workspace is setup to use only the current Java (which must be at least 11 to run a new version of Eclipse) everything works. Otherwise, it is safer to specify Java 11 in the MWE2 launch configurations to make sure they are executed with a real new JDK.

If a user simply has a single JRE configured in the workspace and it corresponds to the default one no problem should happen.

Of course, as you said, if the user relies on the generated TP no problem should happen either.

**Comment by sergio-otero** [comment]
@cdietrich For me, in a brand new XText 2.13 project i have to also add a dependency to  org.eclipse.emf.codegen to make it work

Parent pom.xml:

```
				<plugin>
					<groupId>org.eclipse.xtend</groupId>
					<artifactId>xtend-maven-plugin</artifactId>
					<version>${xtextVersion}</version>
					<executions>
						<execution>
							<goals>
								<goal>compile</goal>
								<goal>xtend-install-debug-info</goal>
								<goal>testCompile</goal>
								<goal>xtend-test-install-debug-info</goal>
							</goals>
						</execution>
					</executions>
					<configuration>
						<outputDirectory>${basedir}/xtend-gen</outputDirectory>
						<testOutputDirectory>${basedir}/xtend-gen</testOutputDirectory>
					</configuration>
					<dependencies>
						<dependency>
							<groupId>org.eclipse.jdt</groupId>
							<artifactId>org.eclipse.jdt.core</artifactId>
							<version>3.12.2</version>
							<exclusions>
								<exclusion>
									<groupId>org.eclipse.platform</groupId>
									<artifactId>org.eclipse.equinox.common</artifactId>
								</exclusion>
								<exclusion>
									<groupId>org.eclipse.platform</groupId>
									<artifactId>org.eclipse.core.runtime</artifactId>
								</exclusion>
							</exclusions>
						</dependency>
						<dependency>
							<groupId>org.eclipse.jdt</groupId>
							<artifactId>org.eclipse.jdt.compiler.apt</artifactId>
							<version>1.2.100</version>
							<exclusions>
								<exclusion>
									<groupId>org.eclipse.platform</groupId>
									<artifactId>org.eclipse.equinox.common</artifactId>
								</exclusion>
								<exclusion>
									<groupId>org.eclipse.platform</groupId>
									<artifactId>org.eclipse.core.runtime</artifactId>
								</exclusion>
							</exclusions>
						</dependency>
						<dependency>
							<groupId>org.eclipse.jdt</groupId>
							<artifactId>org.eclipse.jdt.compiler.tool</artifactId>
							<version>1.2.51</version>
							<exclusions>
								<exclusion>
									<groupId>org.eclipse.platform</groupId>
									<artifactId>org.eclipse.equinox.common</artifactId>
								</exclusion>
								<exclusion>
									<groupId>org.eclipse.platform</groupId>
									<artifactId>org.eclipse.core.runtime</artifactId>
								</exclusion>
							</exclusions>
						</dependency>
						<dependency>
							<groupId>org.eclipse.emf</groupId>
							<artifactId>org.eclipse.emf.codegen</artifactId>
							<version>2.11.0</version>
						</dependency>
						
					</dependencies>
				</plugin>

```

Grammar pom.xml in Mwe2Launcher:

```
					<dependency>
						<groupId>org.eclipse.xtext</groupId>
						<artifactId>org.eclipse.xtext.xtext.generator</artifactId>
						<version>${xtextVersion}</version>
						<exclusions>
							<exclusion>
								<groupId>org.eclipse.platform</groupId>
								<artifactId>org.eclipse.equinox.common</artifactId>
							</exclusion>
							<exclusion>
								<groupId>org.eclipse.platform</groupId>
								<artifactId>org.eclipse.core.runtime</artifactId>
							</exclusion>
						</exclusions>
					</dependency>

```

**Comment by rmollik** [comment]
Hi,

I tried Sergios solution but I still get:

[ERROR] Failed to execute goal org.eclipse.xtend:xtend-maven-plugin:2.11.0:compile (default) on project org.eclipse.osbp.releng.maven.parent.tycho: Execution default of goal org.eclipse.xtend:xtend-maven-plugin:2.11.0:compile failed: Unable to load the mojo 'compile' in the plugin 'org.eclipse.xtend:xtend-maven-plugin:2.11.0' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: org/eclipse/core/runtime/OperationCanceledException has been compiled by a more recent version of the Java Runtime (classfile version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.eclipse.xtend:xtend-maven-plugin:2.11.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/E:/maven/.m2/repository/org/eclipse/xtend/xtend-maven-plugin/2.11.0/xtend-maven-plugin-2.11.0.jar
[ERROR] urls[1] = file:/E:/maven/.m2/repository/org/eclipse/jdt/org.eclipse.jdt.core/3.12.2/org.eclipse.jdt.core-3.12.2.jar
[ERROR] urls[2] = file:/E:/maven/.m2/repository/org/eclipse/platform/org.eclipse.core.resources/3.15.0/org.eclipse.core.resources-3.15.0.jar
[ERROR] urls[3] = file:/E:/maven/.m2/repository/org/eclipse/platform/org.eclipse.core.filesystem/1.9.0/org.eclipse.core.filesystem-1.9.0.jar
[ERROR] urls[4] = file:/E:/maven/.m2/repository/org/eclipse/platform/org.eclipse.equinox.registry/3.10.200/org.eclipse.equinox.registry-3.10.200.jar
[ERROR] urls[5] = file:/E:/maven/.m2/repository/org/eclipse/platform/org.eclipse.text/3.12.0/org.eclipse.text-3.12.0.jar
[ERROR] urls[6] = file:/E:/maven/.m2/repository/org/eclipse/platform/org.eclipse.core.commands/3.10.0/org.eclipse.core.commands-3.10.0.jar
[ERROR] urls[7] = file:/E:/maven/.m2/repository/org/eclipse/platform/org.eclipse.equinox.preferences/3.8.200/org.eclipse.equinox.preferences-3.8.200.jar
[ERROR] urls[8] = file:/E:/maven/.m2/repository/org/eclipse/jdt/org.eclipse.jdt.compiler.apt/1.2.100/org.eclipse.jdt.compiler.apt-1.2.100.jar
[ERROR] urls[9] = file:/E:/maven/.m2/repository/org/eclipse/jdt/org.eclipse.jdt.compiler.tool/1.2.51/org.eclipse.jdt.compiler.tool-1.2.51.jar
[ERROR] urls[10] = file:/E:/maven/.m2/repository/org/eclipse/emf/org.eclipse.emf.codegen/2.11.0/org.eclipse.emf.codegen-2.11.0.jar
[ERROR] urls[11] = file:/E:/maven/.m2/repository/org/eclipse/jdt/org.eclipse.jdt.debug/3.12.0/org.eclipse.jdt.debug-3.12.0.jar
[ERROR] urls[12] = file:/E:/maven/.m2/repository/org/eclipse/platform/org.eclipse.debug.core/3.18.100/org.eclipse.debug.core-3.18.100.jar
[ERROR] urls[13] = file:/E:/maven/.m2/repository/org/eclipse/platform/org.eclipse.core.runtime/3.22.0/org.eclipse.core.runtime-3.22.0.jar
[ERROR] urls[14] = file:/E:/maven/.m2/repository/org/eclipse/platform/org.eclipse.equinox.common/3.15.0/org.eclipse.equinox.common-3.15.0.jar
[ERROR] urls[15] = file:/E:/maven/.m2/repository/org/eclipse/platform/org.eclipse.core.jobs/3.11.0/org.eclipse.core.jobs-3.11.0.jar
[ERROR] urls[16] = file:/E:/maven/.m2/repository/org/eclipse/platform/org.eclipse.core.contenttype/3.7.1000/org.eclipse.core.contenttype-3.7.1000.jar
[ERROR] urls[17] = file:/E:/maven/.m2/repository/org/eclipse/platform/org.eclipse.equinox.app/1.5.100/org.eclipse.equinox.app-1.5.100.jar
[ERROR] urls[18] = file:/E:/maven/.m2/repository/org/eclipse/platform/org.eclipse.core.expressions/3.7.100/org.eclipse.core.expressions-3.7.100.jar
[ERROR] urls[19] = file:/E:/maven/.m2/repository/org/eclipse/jdt/org.eclipse.jdt.launching/3.11.0/org.eclipse.jdt.launching-3.11.0.jar
[ERROR] urls[20] = file:/E:/maven/.m2/repository/org/eclipse/platform/org.eclipse.core.variables/3.5.0/org.eclipse.core.variables-3.5.0.jar
[ERROR] urls[21] = file:/E:/maven/.m2/repository/org/eclipse/platform/org.eclipse.osgi/3.16.300/org.eclipse.osgi-3.16.300.jar
[ERROR] urls[22] = file:/E:/maven/.m2/repository/com/google/guava/guava/19.0-rc3/guava-19.0-rc3.jar
[ERROR] urls[23] = file:/E:/maven/.m2/repository/org/eclipse/xtend/org.eclipse.xtend.core/2.11.0/org.eclipse.xtend.core-2.11.0.jar
[ERROR] urls[24] = file:/E:/maven/.m2/repository/org/eclipse/xtext/org.eclipse.xtext.xbase/2.11.0/org.eclipse.xtext.xbase-2.11.0.jar
[ERROR] urls[25] = file:/E:/maven/.m2/repository/org/eclipse/xtext/org.eclipse.xtext.common.types/2.11.0/org.eclipse.xtext.common.types-2.11.0.jar
[ERROR] urls[26] = file:/E:/maven/.m2/repository/org/eclipse/xtext/org.eclipse.xtext.xbase.lib/2.11.0/org.eclipse.xtext.xbase.lib-2.11.0.jar
[ERROR] urls[27] = file:/E:/maven/.m2/repository/org/eclipse/xtext/org.eclipse.xtext.util/2.11.0/org.eclipse.xtext.util-2.11.0.jar
[ERROR] urls[28] = file:/E:/maven/.m2/repository/org/eclipse/xtext/org.eclipse.xtext.smap/2.11.0/org.eclipse.xtext.smap-2.11.0.jar
[ERROR] urls[29] = file:/E:/maven/.m2/repository/org/eclipse/xtext/org.eclipse.xtext/2.11.0/org.eclipse.xtext-2.11.0.jar
[ERROR] urls[30] = file:/E:/maven/.m2/repository/org/eclipse/xtend/org.eclipse.xtend.lib/2.11.0/org.eclipse.xtend.lib-2.11.0.jar
[ERROR] urls[31] = file:/E:/maven/.m2/repository/org/eclipse/xtend/org.eclipse.xtend.lib.macro/2.11.0/org.eclipse.xtend.lib.macro-2.11.0.jar
[ERROR] urls[32] = file:/E:/maven/.m2/repository/org/eclipse/emf/org.eclipse.emf.common/2.22.0/org.eclipse.emf.common-2.22.0.jar
[ERROR] urls[33] = file:/E:/maven/.m2/repository/org/eclipse/emf/org.eclipse.emf.ecore/2.24.0/org.eclipse.emf.ecore-2.24.0.jar
[ERROR] urls[34] = file:/E:/maven/.m2/repository/com/google/inject/guice/3.0/guice-3.0.jar
[ERROR] urls[35] = file:/E:/maven/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[36] = file:/E:/maven/.m2/repository/log4j/log4j/1.2.16/log4j-1.2.16.jar
[ERROR] urls[37] = file:/E:/maven/.m2/repository/org/ow2/asm/asm-commons/5.0.1/asm-commons-5.0.1.jar
[ERROR] urls[38] = file:/E:/maven/.m2/repository/org/ow2/asm/asm-tree/5.0.1/asm-tree-5.0.1.jar
[ERROR] urls[39] = file:/E:/maven/.m2/repository/org/ow2/asm/asm/5.0.1/asm-5.0.1.jar
[ERROR] urls[40] = file:/E:/maven/.m2/repository/org/eclipse/aether/aether-util/1.0.0.v20140518/aether-util-1.0.0.v20140518.jar
[ERROR] urls[41] = file:/E:/maven/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[42] = file:/E:/maven/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
[ERROR] urls[43] = file:/E:/maven/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.0.M1/org.eclipse.sisu.inject-0.3.0.M1.jar
[ERROR] urls[44] = file:/E:/maven/.m2/repository/org/sonatype/sisu/sisu-guice/3.2.3/sisu-guice-3.2.3-no_aop.jar
[ERROR] urls[45] = file:/E:/maven/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.21/plexus-interpolation-1.21.jar
[ERROR] urls[46] = file:/E:/maven/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar
[ERROR] urls[47] = file:/E:/maven/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[48] = file:/E:/maven/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[49] = file:/E:/maven/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[50] = file:/E:/maven/.m2/repository/org/eclipse/emf/org.eclipse.emf.ecore.xmi/2.16.0/org.eclipse.emf.ecore.xmi-2.16.0.jar
[ERROR] urls[51] = file:/E:/maven/.m2/repository/org/antlr/antlr-runtime/3.2/antlr-runtime-3.2.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>org.eclipse.osbp.releng.maven:org.eclipse.osbp.releng.maven.parent.tycho:0.9.0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR]

**Comment by rmollik** [comment]
What can I do to help solving this?

**Comment by cdietrich** [comment]
@rmollik you need to find out where the bad version is lurking in.
so the easiest is to create a new maven projects
add your dependency list you have inplace for the xtend-maven-plugin and check where the new core.runtime and equinox.common are coming from

**Comment by rmollik** [comment]
OK - I finally got it. The trick was to add all the bundles to the dependencies that might cause the trouble. 
Found them with the -X option for the maven build.
The resulting plugin configuration is:

				<plugin>
					<groupId>org.eclipse.xtend</groupId>
					<artifactId>xtend-maven-plugin</artifactId>
					<version>2.11.0</version>
					<executions>
						<execution>
							<goals>
								<goal>compile</goal>
								<goal>xtend-install-debug-info</goal>
								<goal>testCompile</goal>
								<goal>xtend-test-install-debug-info</goal>
							</goals>
							<configuration>
								<javaSourceVersion>1.7</javaSourceVersion>
								<writeTraceFiles>false</writeTraceFiles>
								<outputDirectory>xtend-gen</outputDirectory>
								<includePluginDependencies>false</includePluginDependencies>
							</configuration>
						</execution>
					</executions>
					<dependencies>
						<dependency>
							<groupId>org.eclipse.jdt</groupId>
							<artifactId>org.eclipse.jdt.core</artifactId>
							<version>3.12.2</version>
						</dependency>
						<dependency>
							<groupId>org.eclipse.jdt</groupId>
							<artifactId>org.eclipse.jdt.compiler.apt</artifactId>
							<version>1.2.100</version>
						</dependency>
						<dependency>
							<groupId>org.eclipse.jdt</groupId>
							<artifactId>org.eclipse.jdt.compiler.tool</artifactId>
							<version>1.2.51</version>
						</dependency>
						<dependency>
							<groupId>org.eclipse.emf</groupId>
							<artifactId>org.eclipse.emf.codegen</artifactId>
							<version>2.11.0</version>
						</dependency>
						<dependency>
							<groupId>org.eclipse.platform</groupId>
							<artifactId>org.eclipse.core.commands</artifactId>
							<version>3.9.800</version>
						</dependency>
						<dependency>
							<groupId>org.eclipse.platform</groupId>
							<artifactId>org.eclipse.core.expressions</artifactId>
							<version>3.7.0</version>
						</dependency>
						<dependency>
							<groupId>org.eclipse.platform</groupId>
							<artifactId>org.eclipse.core.filesystem</artifactId>
							<version>1.7.700</version>
						</dependency>
						<dependency>
							<groupId>org.eclipse.platform</groupId>
							<artifactId>org.eclipse.core.jobs</artifactId>
							<version>3.10.1000</version>
						</dependency>
						<dependency>
							<groupId>org.eclipse.platform</groupId>
							<artifactId>org.eclipse.core.resources</artifactId>
							<version>3.13.900</version>
						</dependency>
						<dependency>
							<groupId>org.eclipse.platform</groupId>
							<artifactId>org.eclipse.core.runtime</artifactId>
							<version>3.20.0</version>
						</dependency>
						<dependency>
							<groupId>org.eclipse.platform</groupId>
							<artifactId>org.eclipse.core.variables</artifactId>
							<version>3.4.800</version>
						</dependency>
						<dependency>
							<groupId>org.eclipse.platform</groupId>
							<artifactId>org.eclipse.debug.core</artifactId>
							<version>3.17.0</version>
						</dependency>
						<dependency>
							<groupId>org.eclipse.platform</groupId>
							<artifactId>org.eclipse.equinox.app</artifactId>
							<version>1.5.0</version>
						</dependency>
						<dependency>
							<groupId>org.eclipse.platform</groupId>
							<artifactId>org.eclipse.equinox.common</artifactId>
							<version>3.14.0</version>
						</dependency>
						<dependency>
							<groupId>org.eclipse.platform</groupId>
							<artifactId>org.eclipse.equinox.preferences</artifactId>
							<version>3.8.100</version>
						</dependency>
						<dependency>
							<groupId>org.eclipse.platform</groupId>
							<artifactId>org.eclipse.equinox.registry</artifactId>
							<version>3.10.0</version>
						</dependency>
						<dependency>
							<groupId>org.eclipse.platform</groupId>
							<artifactId>org.eclipse.osgi</artifactId>
							<version>3.16.100</version>
						</dependency>
						<dependency>
							<groupId>org.eclipse.platform</groupId>
							<artifactId>org.eclipse.text</artifactId>
							<version>3.10.400</version>
						</dependency>
					</dependencies>
						
					<configuration>
						<javaSourceVersion>1.7</javaSourceVersion>
						<writeTraceFiles>false</writeTraceFiles>
						<outputDirectory>xtend-gen</outputDirectory>
					</configuration>
				</plugin>

Thank you all for pointing me into the right direction.

**Comment by DanySK** [comment]
Hi, I have a couple of projects failing this way:

```
0    ERROR Mwe2Launcher       - org/eclipse/core/runtime/OperationCanceledException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
java.lang.UnsupportedClassVersionError: org/eclipse/core/runtime/OperationCanceledException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.run(Mwe2Launcher.java:74)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main(Mwe2Launcher.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
```

Am I being hit by this issue?

**Comment by cdietrich** [comment]
@DanySK  yes

**Comment by Erlix322** [comment]
Any Workaround for gradle?

**Comment by cdietrich** [comment]
see https://github.com/itemis/xtext-reference-projects/pull/184

**Comment by Erlix322** [comment]
Thanks! 

I came here from some typefox repositories examples and got some obscure errors during Tests Stage. 
Your link helped and I added the configurations.all section.

```
dependencies {
	testCompile "org.junit.jupiter:junit-jupiter-api:5.1.0"
	testRuntime "org.junit.jupiter:junit-jupiter-engine:5.1.0"
	testCompile "org.eclipse.xtext:org.eclipse.xtext.testing:${xtextVersion}"
	testCompile "org.eclipse.xtext:org.eclipse.xtext.xbase.testing:${xtextVersion}"
	compile "org.eclipse.xtext:org.eclipse.xtext:${xtextVersion}"
	compile "org.eclipse.xtext:org.eclipse.xtext.xbase:${xtextVersion}"
	
	
	
}


configurations {
	mwe2 {
		extendsFrom compile
	}
}

configurations.all {
	    resolutionStrategy { 
	        eachDependency { DependencyResolveDetails details ->
	            if (details.requested.group == 'org.eclipse.platform' && details.requested.name == 'org.eclipse.core.runtime') {
	                details.useVersion "3.19.0"
	            }
	            if (details.requested.group == 'org.eclipse.platform' && details.requested.name == 'org.eclipse.equinox.common') {
	                details.useVersion("3.13.0")
	            }
	        }
	    }
	}

dependencies {
	mwe2 "org.eclipse.emf:org.eclipse.emf.mwe2.launch:2.9.1.201705291010"
	mwe2 "org.eclipse.xtext:org.eclipse.xtext.common.types:${xtextVersion}"
	mwe2 "org.eclipse.xtext:org.eclipse.xtext.xtext.generator:${xtextVersion}"
	mwe2 "org.eclipse.xtext:xtext-antlr-generator:[2.1.1,3)"
}

task generateXtextLanguage(type: JavaExec) {
	main = 'org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher'
	classpath = configurations.mwe2
	inputs.file "src/main/java/io/typefox/examples/theia/states/GenerateStates.mwe2"
	inputs.file "src/main/java/io/typefox/examples/theia/states/States.xtext"
	outputs.dir "src/main/xtext-gen"
	args += "src/main/java/io/typefox/examples/theia/states/GenerateStates.mwe2"
	args += "-p"
	args += "rootPath=/${projectDir}/.."
}

test {
	useJUnitPlatform()
}
generateXtext.dependsOn(generateXtextLanguage)
clean.dependsOn(cleanGenerateXtextLanguage)
eclipse.classpath.plusConfigurations += [configurations.mwe2]
```

**Comment by boris-unckel** [comment]
I filled a bug at eclipse equinox [https://bugs.eclipse.org/bugs/show_bug.cgi?id=574365](https://bugs.eclipse.org/bugs/show_bug.cgi?id=574365) Please check/fix/add extra info.

**Comment by iloveeclipse** [comment]
I've answered : https://bugs.eclipse.org/bugs/show_bug.cgi?id=574365#c1

Was the minor version segment change not enough? Why?

**Comment by cdietrich** [comment]
@iloveeclipse unfortunately platform/jdt and emf maven artifacts have ranges of death `[3.something, 4.0)` so ALL new minor versions will ne considered "fine"

https://search.maven.org/artifact/org.eclipse.jdt/org.eclipse.jdt.core/3.23.0/jar
https://search.maven.org/artifact/org.eclipse.emf/org.eclipse.emf.ecore/2.22.0/jar
https://search.maven.org/artifact/org.eclipse.platform/org.eclipse.core.runtime/3.19.0/jar

**Comment by iloveeclipse** [comment]
Can you "pin" the bundles in question to a specific version in the build files somehow?

**Comment by cdietrich** [comment]
Yes this is what we already do but a handful of usecases slipped through where the current approach of using a maven bom does not work, but we have workarounds for all of them so far

**Comment by DanySK** [comment]
Is there no way to lock dependencies in Maven? To prevent these transitive dependencies issues, it's a best practice in [Gradle](https://docs.gradle.org/current/userguide/dependency_locking.html) and other build systems.

**Comment by LuluDavid** [comment]
Hi,
I have similar issues with gradle4/java8 with a project which applies plugin xtend (version 1.0.21).
I tried to enforce org.eclipse.equinox.common's version to 3.0.9 at first with substitution rules :
```gradle
configurations.all {
   resolutionStrategy {
      dependencySubstitution {
         // TO ENFORCE org.eclipse.platform:org.eclipse.equinox.common:3.9.0
         substitute module('org.eclipse.platform:org.eclipse.equinox.common') with module('org.eclipse.platform:org.eclipse.equinox.common:3.9.0')
      }
   }
}
```
Which did not work. I also tried something similar to [this solution](https://github.com/eclipse/xtext/issues/1976#issuecomment-862141814), and could not make it work. I also tried investigating it with debug mode, but it seems that the problem comes from detached configurations which are not listed in the project's dependencies (with ```./gradlew app:dependencyInsight --dependency org.eclipse.equinox.common``` for instance).  
I also tried things like forcing versions (force = true, ...) and I still could not make it work. Any new workarounds that I might try ?  

Thanks for reading.

**Comment by cdietrich** [comment]
@LuluDavid  can you provide a reproducer or a build scan.
does the dependencyInsight also investigate the plugin deps?

**Comment by LuluDavid** [comment]
Well it's a shame, but I don't think I am allowed to share any of my code or to use gradle scan. I have lots of resources so as a gradle beginner, I do not know if it would be easy to do a reproducer.

DependencyInsight only seems to track the dependency in required projects & dependencies though, as xtend does not appear when I do the command above. Would you know some commands that I might try for further understanding.

Sorry for bothering, and thanks for the quick answer !

**Comment by cdietrich** [comment]
maybe you can run gradle with debug logging to see more where the bad version is
xtend compilation, ....

**Comment by boris-unckel** [comment]
@cdietrich Christian, is there a central solution possible with a new version of xtext or is a fix at the upstream projects necessary? If a xtext solution is possible, when do you estimate to publish it with which version?

**Comment by LorenzoBettini** [comment]
> Is there no way to lock dependencies in Maven? To prevent these transitive dependencies issues, it's a best practice in [Gradle](https://docs.gradle.org/current/userguide/dependency_locking.html) and other build systems.

Yes, there is and we already employ that, but it is not used for dependencies in a plugin configuration. It's used only for dependencies of the projects

**Comment by cdietrich** [comment]
there is no central solution for ALL usecases yet.
i cannot tell if anything can be changed on gradle side and how long it will take
i am also not sure where else the problem is burried and oes not show up.

**Comment by LuluDavid** [comment]
@cdietrich Well the debug output does not show any obvious anomalies, except that the incorrect versions of org.eclipse.equinox.common (& thus org.eclipse.core.runtime, org.eclipse.text, ...) are downloaded for "detachedConfiguration1" & "detachedConfiguration2", which seem to be internal resolution configurations (and are not listed with dependencyInsight, which is sad). Also, it downloads by default all versions of org.eclipse.equinox.common and seems to choose the most recent one by default, without being affected by my custom rules to enforce the version : 
```
12:18:30.597 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Download https://repo.maven.apache.org/maven2/org/eclipse/platform/org.eclipse.equinox.common/maven-metadata.xml'
12:18:30.597 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Download https://repo.maven.apache.org/maven2/org/eclipse/platform/org.eclipse.equinox.common/maven-metadata.xml' completed
12:18:30.599 [DEBUG] [org.gradle.api.internal.artifacts.repositories.maven.MavenMetadataLoader] parsing maven-metadata: org.gradle.internal.resource.local.DefaultLocallyAvailableExternalResource@4b3806c5
12:18:30.600 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.modulecache.dynamicversions.DefaultModuleVersionsCache] Caching version list in module versions cache: Using '[3.8.0, 3.9.0, 3.10.0, 3.10.100, 3.10.200, 3.10.300, 3.10.400, 3.10.500, 3.10.600, 3.11.0, 3.12.0, 3.13.0, 3.14.0, 3.14.100, 3.15.0]' for 'org.eclipse.platform:org.eclipse.equinox.common'
12:18:30.600 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading https://repo.maven.apache.org/maven2/org/eclipse/platform/org.eclipse.equinox.common/3.15.0/org.eclipse.equinox.common-3.15.0.pom
12:18:30.601 [DEBUG] [org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor] Constructing external resource: https://repo.maven.apache.org/maven2/org/eclipse/platform/org.eclipse.equinox.common/3.15.0/org.eclipse.equinox.common-3.15.0.pom
12:18:30.601 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Download https://repo.maven.apache.org/maven2/org/eclipse/platform/org.eclipse.equinox.common/3.15.0/org.eclipse.equinox.common-3.15.0.pom' started
12:18:30.601 [DEBUG] [org.gradle.internal.resource.transport.http.HttpResourceAccessor] Constructing external resource: https://repo.maven.apache.org/maven2/org/eclipse/platform/org.eclipse.equinox.common/3.15.0/org.eclipse.equinox.common-3.15.0.pom
12:18:30.601 [DEBUG] [org.gradle.internal.resource.transport.http.HttpClientHelper] Performing HTTP GET: https://repo.maven.apache.org/maven2/org/eclipse/platform/org.eclipse.equinox.common/3.15.0/org.eclipse.equinox.common-3.15.0.pom
```
The graph resolver does not output any information about causality, so it's difficult to work it out with that.  
For the workaround, I just added the same lines as your commit in the only build.gradle where I use ```apply plugin: 'org.xtext.xtend'```, right under it. Am I doing this wrong ?

**Comment by cdietrich** [comment]
i have it at the parent. it will do someting for projects that have xtend plugin anyway only, so no harm

**Comment by lidochca** [comment]
> @oehme no Xtext uses emf, emf has ranges for core.runtime and equinox.common
> Xtext also has deps to core.runtime and equinox.common but some of them are optional and are not in pom
> so instead of the plaform version Xtext likes to have the newest are pulled

Hello, We are also having this issue. And we can't update to java 8. It's difficult to follow your discussions. Could you please summarize what configuration we could change in pom.xml file ?
It worked with following in pom.xml, and now it's not.
<emf-url>https://download.eclipse.org/modeling/emf/emf/builds/release/latest/</emf-url>
<mwe-url>https://download.eclipse.org/modeling/emft/mwe/updates/releases/2.11.3/</mwe-url>
<xpand-url>https://download.eclipse.org/modeling/m2t/xpand/updates/releases/</xpand-url>
<xtext-url>https://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.22.0/</xtext-url>
<eclipse-url>https://download.eclipse.org/releases/2020-03/202003181000</eclipse-url>

How to prevent from downloading latest org.eclipse.jdt.core ?
/org/eclipse/jdt/org.eclipse.jdt.core/3.26.0/org.eclipse.jdt.core-3.26.0.pom
    
I don't mind to use previous versions of the plugins. I tried 
<emf-url>https://download.eclipse.org/modeling/emf/emf/builds/release/2.22</emf-url>
and still getting same issue.
"...has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0"

Thank you, in advance

**Comment by cdietrich** [comment]
@lidochca  do you use maven or maven tycho and which Xtext version do you use? 2.22?
you can try one of these 3 

https://github.com/itemis/xtext-reference-projects/pull/186
https://github.com/itemis/xtext-reference-projects/pull/183
https://github.com/itemis/xtext-reference-projects/pull/182

**Comment by lidochca** [comment]
> @lidochca do you use maven or maven tycho and which Xtext version do you use? 2.22?
> you can try one of these 3
> 
> [itemis/xtext-reference-projects#186](https://github.com/itemis/xtext-reference-projects/pull/186)
> [itemis/xtext-reference-projects#183](https://github.com/itemis/xtext-reference-projects/pull/183)
> [itemis/xtext-reference-projects#182](https://github.com/itemis/xtext-reference-projects/pull/182)

Thanks @cdietrich 
I'm using Maven 3.6.0, java 1.8, in pom.xml building with tycho 1.7

**Comment by MarkRx** [comment]
I've run into something like this before with https://github.com/eclipse/xtext-xtend/issues/601. I have a hotfix gradle plugin I apply to all our projects so we can continue to compile against and target Java 6 (gross I know). You can create a gradle plugin with this to work around the issue. It's not pretty but it works.

```
package com.paychex.eba.xtextjava6hotfix;

import org.gradle.api.Action;
import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.api.artifacts.Configuration;
import org.xtext.gradle.tasks.XtextGenerate;

/**
 * Hotfix that puts java 6 compatible JDT libraries in the front of the classpath used to compile xtend
 */
public class XtextJava6HotfixPlugin implements Plugin<Project> {
    
    @Override
    public void apply(final Project project) {
        final Configuration config = project.getConfigurations().create("xtexthotfix");
        
        project.getDependencies().add("xtexthotfix", "org.eclipse.jdt:org.eclipse.jdt.core:3.10.0");
        
        // 3.15 was compiled with java 11 and because of ranges a transitive dependency ends up picking it up
        project.getDependencies().add("xtexthotfix", "org.eclipse.platform:org.eclipse.equinox.common:3.14.100");
        
        // We need to do after evaluate because of the order that task events are fired. It appears a task is created, 
        // an event is fired, and then the task is configured. We unfortunately need to be notified after a task is
        // configured because we need to access some of the task properties. To work around this we modify the task
        // configuration after the project is evaluated.
        // See https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskContainer.java#L173
        project.afterEvaluate(new Action<Project>() {

            @Override
            public void execute(final Project project) {
                project.getTasks().withType(XtextGenerate.class, new Action<XtextGenerate>() {

                    @Override
                    public void execute(XtextGenerate task) {
                        task.setXtextClasspath(project.files(config, task.getXtextClasspath()));
                    }

                });

            }
        });
    }
}
```

**Comment by LuluDavid** [comment]
@cdietrich my bad it does not work because I am under xtext 2.13 so the BOM does not exist for my configuration (the condition about "Tooling" in the name of my configurations is never triggered by the way).

**Comment by cdietrich** [comment]
then i assume you need to do this https://github.com/eclipse/xtext/issues/1976#issuecomment-862141814

**Comment by lidochca** [comment]
> @lidochca do you use maven or maven tycho and which Xtext version do you use? 2.22?
> you can try one of these 3
> 
> [itemis/xtext-reference-projects#186](https://github.com/itemis/xtext-reference-projects/pull/186)
> [itemis/xtext-reference-projects#183](https://github.com/itemis/xtext-reference-projects/pull/183)
> [itemis/xtext-reference-projects#182](https://github.com/itemis/xtext-reference-projects/pull/182)

Thanks @cdietrich
The solution itemis/xtext-reference-projects#186 worked for us. Thanks a lot.

**Comment by LuluDavid** [comment]
Well, after lots of attempts, for a gradle build, what worked for me was to combine @cdietrich's [workaround](https://github.com/eclipse/xtext/issues/1976#issuecomment-862141814) with @MarkRx's second tip applied to all my build.gradle's that eventually have task generateXtext (which include org.eclipse.xtend in their plugin section I guess).  
Thanks for both answers, I was getting a bit desperate !

**Comment by hyp3rz** [comment]
Hi all, has anyone figured out the workaround for a maven build, xtext/xtend v 2.10.0, with JDk1.8? I/we have tried multiple approaches but did not figure out a proper way to compile.

In our project we are using a combination of plugins maven-eclipse-plugin, xtend-maven-plugin, tycho-maven-plugin

If we figure out a solution will paste of course the details that maybe would help others. Thank you!

**Comment by rmollik** [comment]
> Hi all, has anyone figured out the workaround for a maven build, xtext/xtend v 2.10.0, with JDk1.8? I/we have tried multiple approaches but did not figure out a proper way to compile.
> 
> In our project we are using a combination of plugins maven-eclipse-plugin, xtend-maven-plugin, tycho-maven-plugin
> 
> If we figure out a solution will paste of course the details that maybe would help others. Thank you!

This helped me - I added explicit dependencies instead of trying to exclude what made it fail. Might not be the most elegant way, but it worked for my szenario.

https://github.com/eclipse/xtext/issues/1976#issuecomment-864098248

**Comment by hyp3rz** [comment]
> > Hi all, has anyone figured out the workaround for a maven build, xtext/xtend v 2.10.0, with JDk1.8? I/we have tried multiple approaches but did not figure out a proper way to compile.
> > In our project we are using a combination of plugins maven-eclipse-plugin, xtend-maven-plugin, tycho-maven-plugin
> > If we figure out a solution will paste of course the details that maybe would help others. Thank you!
> 
> This helped me - I added explicit dependencies instead of trying to exclude what made it fail. Might not be the most elegant way, but it worked for my szenario.
> 
> [#1976 (comment)](https://github.com/eclipse/xtext/issues/1976#issuecomment-864098248)

This is fenomenal, I am not sure how I missed this one! Thank you so much! We were able to compile/build now sanitizing. I was halfway there with the deps but this really did the trick.

**Comment by cdietrich** [comment]
workarounds in place now.
we still need a clean solution.
otherwise the problem will reappear when platform updates to Java 17 and we are still on Java 11

**Comment by szarnekow** [comment]
If I understood @LorenzoBettini proposal correctly, the dependencies need to be pinned along the dependency chain of the bundles used from the maven-exec-plugin and the xtext-generator-plugin. Basically where some emf-dependency is being used, we need to make the versions of the necessary (transitive) dependencies explicit based on the versions in the BOM. We should start with xtext.generator.

Is the correct, @LorenzoBettini ?

**Comment by LorenzoBettini** [comment]
@szarnekow it's basically correct:

- actually, such versions are already pinned in the Xtext dev BOM, so it's just a matter of mentioning the dependencies (without versions), including the transitive ones, e.g., in the xtext.generator's POM (actually in the Gradle file, since from that the POM will be generated) and if the BOM is imported Maven will take the versions of the BOM
- that's required for every dependency that has a version range instead of a fixed version, and that includes EMF artifacts and basically all Platform and JDT ones
- the chain has to be followed for all the dependencies that have version range

This holds for our use of maven-exec-plugin. Concerning xtext-generator-plugin you mean xtext-maven-plugin, right? The xtext-maven-plugin should be fine with that respect if I remember correctly, I mean its dependencies should be already pinned.

IMPORTANT: this is crucial because the BOM is NOT used by Maven for the <dependencies> of a plugin configuration. That's why if you simply use a plugin without further dependencies in the configuration you shouldn't experience a problem, of course if its dependencies versions are already taken care of. That's the case of the xtend-maven-plugin which was fixed when the BOM was introduced. You typically use that without further dependencies in its configuration.

**Comment by cdietrich** [comment]
hmmm so this would solve it for maven, but i still have no clue regarding xtend and gradle. i guess we have to live with the workaround there or encode the workaround into the plugin.

**Comment by LorenzoBettini** [comment]
If gradle uses the BOM then it should be the same. Concerning the `xtend-maven-plugin` it should have been fixed long ago (by pinning the versions in the Xtext BOM). Concerning the `xtext-maven-plugin` it should be the same, as long as one does not list an additional dependency in the configuration that has version ranges (or it transitively depends on a dependency with version ranges).

Maybe it's worthwhile to stress that again: the "bad guys" are those using version ranges without respecting semantic versioning. It's not really EMF to blame, it's the platform bundles that now require Java 11 without increasing the major version...

**Comment by LorenzoBettini** [comment]
I'd like to draw the committers' attention (again) to my proposal https://github.com/eclipse/xtext-core/pull/1714 which fixes the problem for good, without workarounds...

**Comment by cdietrich** [comment]
pinned deps in generator and removed workaround for it

**Comment by cdietrich** [comment]
should be fixed now
